/* ═══════════════════════════════════════════
   INSTANT PURSUIT — Shared Data & Utilities
   ═══════════════════════════════════════════ */
const SITE = { name: 'Instant Pursuit', tagline: 'Navigate your career with confidence.', url: 'https://instantpursuit.in', icon: '🧭' };
const NAV_LINKS = [
  { href: 'index.html', label: 'Home', icon: '🏠' },
  { href: 'explore.html', label: 'Explore', icon: '🗺️' },
  { href: 'blog.html', label: 'Blog', icon: '✍️' },
  { href: 'about.html', label: 'About', icon: '📖' },
];
function getTheme(){return localStorage.getItem('ip-theme')||'dark'}
function setTheme(t){document.documentElement.setAttribute('data-theme',t);localStorage.setItem('ip-theme',t);const b=document.querySelector('.theme-toggle');if(b)b.textContent=t==='dark'?'☀️':'🌙'}
function toggleTheme(){setTheme(getTheme()==='dark'?'light':'dark')}
function initTheme(){setTheme(getTheme())}
function loadData(k,f){try{const d=localStorage.getItem(k);return d?JSON.parse(d):f}catch{return f}}
function saveData(k,v){localStorage.setItem(k,JSON.stringify(v))}
function injectNav(){
  const cur=location.pathname.split('/').pop()||'index.html';
  const n=document.createElement('nav');n.className='ip-nav';
  n.innerHTML=`<div class="ip-nav-inner"><a href="index.html" class="ip-nav-logo"><span>${SITE.icon}</span> ${SITE.name}</a><div class="ip-nav-links">${NAV_LINKS.map(l=>`<a href="${l.href}" class="${cur===l.href?'active':''}">${l.label}</a>`).join('')}</div><div class="ip-nav-right"><button class="theme-toggle" onclick="toggleTheme()" title="Toggle theme">🌙</button><button class="ip-hamburger" onclick="document.querySelector('.ip-mobile-menu').classList.toggle('open')" aria-label="Menu"><span></span><span></span><span></span></button></div></div><div class="ip-mobile-menu">${NAV_LINKS.map(l=>`<a href="${l.href}" class="${cur===l.href?'active':''}">${l.icon} ${l.label}</a>`).join('')}</div>`;
  document.body.prepend(n);
}
function injectFooter(){
  const f=document.createElement('footer');f.className='ip-footer';
  f.innerHTML=`<div class="ip-footer-logo">${SITE.icon} ${SITE.name}</div><div class="ip-footer-tagline">${SITE.tagline}</div><div class="ip-footer-links">${NAV_LINKS.map(l=>`<a href="${l.href}">${l.label}</a>`).join('')}</div><div class="ip-footer-disclaimer">Disclaimer: This website is maintained in a personal capacity for educational and informational purposes only. It does not represent the views of the Government of India or any department thereof.</div><div class="ip-footer-copy">&copy; 2026 ${SITE.name}. Open source &amp; free to use.</div>`;
  document.body.appendChild(f);
}
function initPage(){
  initTheme();
  if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',function(){injectNav();injectFooter()})}
  else{injectNav();injectFooter()}
}

// ═══════════════════════════════════════════
// CAREER DATA — Full tree with details
// ═══════════════════════════════════════════
const DEFAULT_CAREER_DATA = {
"6-10":{label:"Classes 6–10",description:"Foundation years — build your base!",icon:"📚",children:{
"science":{label:"Science Stream",icon:"🔬",info:{benefits:["Strong analytical thinking","Wide career options in tech, medicine, research","High demand globally"],drawbacks:["Requires strong math fundamentals","Can be intensive and competitive"],tip:"Best if you love experiments and problem-solving."},children:{
"pcm":{label:"PCM (Physics, Chemistry, Maths)",icon:"🧮",info:{benefits:["Opens doors to engineering, tech, data science","Highest earning potential streams"],drawbacks:["Very competitive entrance exams (JEE)","Abstract concepts can be challenging"],tip:"If you love puzzles, logic, and building things — PCM is your playground."},children:{
"engineering":{label:"Engineering (B.Tech / B.E.)",icon:"⚙️",info:{benefits:["Enormous job market","High starting salaries","Diverse specializations","Global opportunities"],drawbacks:["4-year commitment","Intense entrance exams","Quality varies across colleges"],tip:"Focus on a branch that excites you, not just placement stats.",detail:"Engineering remains India's most popular undergraduate pathway, with over 3,000 colleges offering B.Tech/B.E. degrees. The key differentiator is college tier — IITs, NITs, and BITS produce vastly different outcomes than lower-tier private colleges. Branch selection at JEE counselling is consequential, though lateral skill-building (coding, internships) can bridge the gap.",topColleges:["IIT Bombay","IIT Delhi","IIT Madras","BITS Pilani","NIT Trichy","IIIT Hyderabad"],topRecruiters:["Google","Microsoft","Amazon","Goldman Sachs","Qualcomm","TCS","Infosys","L&T"],avgCTC:"₹4-25 LPA (varies by college tier)"},children:{
"cs":{label:"Computer Science",icon:"💻",info:{benefits:["Highest demand in job market","Startup-friendly skills","Remote work options"],drawbacks:["Rapidly evolving — constant learning","Highly competitive","Screen-heavy lifestyle"],tip:"Learn to code early — even basic Python opens huge doors.",detail:"Computer Science is the undisputed king of engineering branches by placements. CSE graduates from top colleges command ₹15-50 LPA, with some IIT grads receiving international offers above ₹1 Cr. The curriculum covers algorithms, OS, databases, networks, and AI/ML. The real edge comes from self-driven learning — competitive programming, open-source, and personal projects.",topColleges:["IIT Bombay","IIT Delhi","IIT Madras","IIIT Hyderabad","BITS Pilani","IIT Kanpur"],topRecruiters:["Google","Microsoft","Amazon","Meta","Apple","Goldman Sachs","Uber","Flipkart","Atlassian"],avgCTC:"₹8-40 LPA (top colleges)"},children:{
"sde":{label:"Software Development",icon:"🖥️",info:{benefits:["Core tech role everywhere","Product-building skills","Remote-friendly"],drawbacks:["Leetcode grind","Long startup hours","Burnout common"],tip:"Build projects on GitHub — they speak louder than CGPA.",detail:"Software Development Engineers design, build, and maintain applications powering modern businesses. From frontend web apps to backend microservices and mobile apps, SDE is the most versatile tech role. The interview process at top companies focuses on DSA, system design, and behavioral questions.",topColleges:["IIT Bombay","IIT Delhi","IIIT Hyderabad","BITS Pilani"],topRecruiters:["Google","Microsoft","Amazon","Flipkart","Atlassian","Uber","Razorpay","PhonePe"],avgCTC:"₹12-50 LPA"},children:{}},
"datascience":{label:"Data Science / Analytics",icon:"📊",info:{benefits:["Data-driven decisions","Every industry needs it","Stats + coding mix"],drawbacks:["Needs strong statistics","Tool landscape changes fast"],tip:"Master SQL and Python — bread and butter of data roles.",detail:"Data Science sits at the intersection of statistics, programming, and domain expertise. Companies now want specialists (NLP, CV, recommendation systems) over generalists. A strong statistics foundation is non-negotiable.",topColleges:["ISI Kolkata","IIT Madras","IIT Bombay","IIIT Hyderabad","CMI Chennai"],topRecruiters:["Google","Amazon","McKinsey","Tiger Analytics","Fractal","Mu Sigma","Walmart Labs"],avgCTC:"₹10-30 LPA"},children:{}},
"cybersecurity":{label:"Cybersecurity",icon:"🔐",info:{benefits:["Massive talent shortage","Critical for every org","Ethical hacking is exciting"],drawbacks:["Constant threat updates","Certifications expensive","On-call pressure"],tip:"Start with CompTIA Security+ and CTF competitions.",detail:"Cybersecurity professionals protect organizations from digital threats. India alone needs over 1 million cybersecurity professionals and the gap is widening. Bug bounty platforms like HackerOne offer lucrative side income.",topColleges:["IIT Kanpur","IIT Madras","IIIT Delhi","NIT Surathkal"],topRecruiters:["Deloitte","PwC","CrowdStrike","Palo Alto Networks","Cisco","TCS"],avgCTC:"₹8-25 LPA"},children:{}},
"devops":{label:"DevOps / Cloud",icon:"☁️",info:{benefits:["Bridges dev and ops","Cloud skills future-proof","Automation focus"],drawbacks:["Steep learning curve","On-call duties","Less creative than frontend"],tip:"Get AWS Certified — most recognized cloud certification.",detail:"DevOps engineers automate the pipeline between development and operations. They manage CI/CD, containerization (Docker, Kubernetes), infrastructure-as-code (Terraform), and cloud platforms. With every company moving to cloud, DevOps/SRE roles are essential.",topColleges:["IIT Bombay","BITS Pilani","NIT Trichy","IIIT Hyderabad"],topRecruiters:["Amazon AWS","Microsoft Azure","Google Cloud","Hashicorp","Red Hat","Razorpay"],avgCTC:"₹10-35 LPA"},children:{}}}},
"mech":{label:"Mechanical Engineering",icon:"🔧",info:{benefits:["Core engineering fundamentals","Auto, aero, manufacturing sectors","Design & innovation"],drawbacks:["Fewer IT jobs","May need masters for research","Limited remote work"],tip:"Combine with coding (CAD, robotics) for best opportunities.",detail:"Mechanical Engineering covers thermodynamics, fluid mechanics, manufacturing, and machine design. The smart move is combining mechanical skills with emerging tech — robotics, 3D printing, EV design, and CFD. Mech engineers with coding skills are significantly more employable.",topColleges:["IIT Bombay","IIT Delhi","IIT Madras","IIT Kanpur","NIT Trichy","BITS Pilani"],topRecruiters:["Tata Motors","Mahindra","Maruti Suzuki","Bosch","L&T","ISRO","DRDO","Cummins"],avgCTC:"₹5-15 LPA"},children:{
"automotive":{label:"Automotive Engineering",icon:"🚗",info:{benefits:["EV revolution creating roles","Work with top OEMs"],drawbacks:["Location-dependent","Slow initial growth"],tip:"EV and autonomous vehicle skills are the golden ticket.",detail:"The automotive sector is undergoing its biggest transformation with EVs. Companies like Tata Motors, Ola Electric, and Ather Energy are hiring for battery tech, motor design, and vehicle software.",topColleges:["IIT Madras","IIT Delhi","BITS Pilani","COEP Pune"],topRecruiters:["Tata Motors","Mahindra","Ola Electric","Ather Energy","Hyundai India","Bosch"],avgCTC:"₹5-15 LPA"},children:{}},
"robotics":{label:"Robotics & Automation",icon:"🦾",info:{benefits:["Cutting-edge field","Industry 4.0 demand","Interdisciplinary"],drawbacks:["Requires coding + hardware","Expensive self-learning"],tip:"ROS (Robot Operating System) is the skill to invest in.",detail:"Robotics combines mechanical, electrical, and computer science. Industrial and service robots are growing rapidly. In India, Addverb Technologies and GreyOrange are leading players.",topColleges:["IIT Bombay","IIT Madras","IIIT Hyderabad"],topRecruiters:["Addverb Technologies","GreyOrange","Bosch","ABB","Amazon Robotics"],avgCTC:"₹6-20 LPA"},children:{}},
"aerospace":{label:"Aerospace / Defence",icon:"✈️",info:{benefits:["Prestigious sector","ISRO, DRDO, HAL","High intellectual satisfaction"],drawbacks:["Limited private sector","Security clearance","Slow hiring"],tip:"GATE exam is your gateway to ISRO.",detail:"India's aerospace sector is at an inflection point with ISRO's commercial arm, private players like Skyroot and Agnikul, and defence modernization. The Indian Space Policy 2023 opened the sector to private investment.",topColleges:["IIT Bombay","IIT Madras","IIT Kanpur","IIST Trivandrum"],topRecruiters:["ISRO","DRDO","HAL","Skyroot Aerospace","Agnikul","Boeing India"],avgCTC:"₹6-18 LPA"},children:{}}}},
"ece":{label:"Electronics & Communication",icon:"📡",info:{benefits:["VLSI, telecom, IoT industries","Hardware & software mix","Semiconductor boom"],drawbacks:["Overlap with CS","Lab-intensive","Hardware roles less flexible"],tip:"Focus on embedded systems or VLSI for niche advantage.",detail:"ECE bridges the physical and digital worlds. India's ₹76,000 crore semiconductor mission has made ECE graduates more valuable. VLSI design, embedded systems, IoT, and 5G are high-growth areas.",topColleges:["IIT Bombay","IIT Madras","NIT Trichy","BITS Pilani","IIIT Hyderabad"],topRecruiters:["Qualcomm","Intel","Texas Instruments","Samsung","MediaTek","Broadcom","Nvidia"],avgCTC:"₹6-20 LPA"},children:{
"vlsi":{label:"VLSI / Chip Design",icon:"🔌",info:{benefits:["India semiconductor push","Deep technical work"],drawbacks:["Very niche","Long learning curve","Limited to Bangalore/Hyderabad"],tip:"Learn Verilog/VHDL and EDA tools.",detail:"VLSI engineers design the chips that power every electronic device. With India's semiconductor mission, this is a strategic national priority. Bangalore and Hyderabad are the twin hubs.",topColleges:["IIT Bombay","IIT Madras","IISc Bangalore","IIIT Hyderabad"],topRecruiters:["Intel","Qualcomm","Texas Instruments","Synopsys","Cadence","Samsung","AMD","Nvidia"],avgCTC:"₹10-30 LPA"},children:{}},
"iot":{label:"IoT & Embedded Systems",icon:"📶",info:{benefits:["Smart devices everywhere","Startup opportunities"],drawbacks:["Hardware debugging painful","Fragmented ecosystem"],tip:"Build a home automation project — best portfolio piece.",detail:"IoT connects physical devices to the internet for smart homes, industrial monitoring, and wearable health devices. Embedded engineers write firmware in C/C++ for microcontrollers.",topColleges:["IIT Bombay","BITS Pilani","NIT Trichy","VIT"],topRecruiters:["Bosch","Honeywell","Siemens","Samsung","Tata Elxsi","KPIT"],avgCTC:"₹5-18 LPA"},children:{}}}},
"civil":{label:"Civil Engineering",icon:"🏗️",info:{benefits:["Infrastructure always in demand","Govt job options","Tangible impact"],drawbacks:["Field work in tough conditions","Slower growth vs IT"],tip:"GATE score is crucial for PSU recruitment.",detail:"Civil Engineering covers structural design, construction management, transportation, and water resources. India's highway, metro, and smart city projects ensure steady demand. PSUs (NHAI, NHPC) and L&T are major employers.",topColleges:["IIT Bombay","IIT Delhi","IIT Madras","IIT Roorkee","NIT Trichy"],topRecruiters:["L&T Construction","Tata Projects","NHAI","CPWD","Shapoorji Pallonji"],avgCTC:"₹4-12 LPA"},children:{}},
"electrical":{label:"Electrical Engineering",icon:"⚡",info:{benefits:["Power sector backbone","Govt PSU jobs","Renewable energy growth"],drawbacks:["Field postings common","Less glamorous perception"],tip:"Renewable energy and EVs are making this hot again.",detail:"Electrical Engineering covers power generation, transmission, and distribution. The transition to renewables and EVs has revitalized the field. PSUs like NTPC and PGCIL offer excellent packages through GATE.",topColleges:["IIT Bombay","IIT Delhi","IIT Madras","IIT Kanpur","NIT Trichy"],topRecruiters:["NTPC","PGCIL","BHEL","Tata Power","Adani Green","Siemens","Schneider Electric"],avgCTC:"₹5-14 LPA"},children:{}},
"aiml":{label:"AI & Machine Learning",icon:"🤖",info:{benefits:["Cutting edge","Extremely high demand","Research + industry paths"],drawbacks:["Requires strong math","Rapidly changing","Curriculum evolving"],tip:"Build projects on Kaggle and GitHub — portfolio > marks.",detail:"AI/ML is now a dedicated B.Tech branch at many IITs. The curriculum covers deep learning, NLP, computer vision, and reinforcement learning. The field rewards strong math (linear algebra, probability) and hands-on project experience.",topColleges:["IIT Bombay","IIT Hyderabad","IIT Madras","IIIT Hyderabad","BITS Pilani"],topRecruiters:["Google DeepMind","Microsoft Research","Amazon AI","Nvidia","Adobe Research","Flipkart"],avgCTC:"₹12-50 LPA (top tier)"},children:{
"nlp":{label:"NLP / LLMs",icon:"🗣️",info:{benefits:["Hottest AI subfield","Research + product roles"],drawbacks:["Compute-intensive","Moves extremely fast"],tip:"Fine-tune an open-source LLM — best portfolio piece in 2026.",detail:"NLP has been transformed by Large Language Models. NLP engineers work on chatbots, document understanding, translation, and text generation. Indian companies like Sarvam AI and Krutrim are building India-specific language models.",topColleges:["IIT Bombay","IIIT Hyderabad","IIT Madras","IISc"],topRecruiters:["Google","Microsoft","Meta","Anthropic","Sarvam AI","Adobe"],avgCTC:"₹15-60 LPA"},children:{}},
"cv":{label:"Computer Vision",icon:"👁️",info:{benefits:["Self-driving cars, medical imaging","Tangible visual output"],drawbacks:["Large dataset needs","GPU-intensive"],tip:"Start with OpenCV, then PyTorch.",detail:"Computer Vision enables machines to interpret visual data. Applications include autonomous driving, medical imaging, quality inspection, and AR.",topColleges:["IIT Bombay","IISc Bangalore","IIIT Hyderabad"],topRecruiters:["Google","Nvidia","Tesla","Qualcomm","Samsung"],avgCTC:"₹12-40 LPA"},children:{}}}},
"chemical":{label:"Chemical Engineering",icon:"🧪",info:{benefits:["Petrochemical, pharma, FMCG","PSU opportunities"],drawbacks:["Limited private roles","Factory locations"],tip:"Combine with data skills for process analytics.",detail:"Chemical engineers optimize processes transforming raw materials into products. PSUs like IOCL, BPCL recruit through GATE. Private roles exist in FMCG and specialty chemicals.",topColleges:["IIT Bombay","IIT Madras","IIT Delhi","NIT Trichy","BITS Pilani"],topRecruiters:["IOCL","BPCL","Reliance","HUL","Shell","BASF"],avgCTC:"₹5-15 LPA"},children:{}},
"biotech":{label:"Biotech Engineering",icon:"🧬",info:{benefits:["Post-COVID pharma boom","Research-oriented","Genomics"],drawbacks:["Masters almost mandatory","Slow start","Limited core companies"],tip:"Bioinformatics (biology + coding) is where the real jobs are.",detail:"Biotechnology applies biological systems for healthcare, agriculture, and industrial products. Career prospects with just B.Tech are limited — most impactful roles require M.Tech, MS, or PhD. Bioinformatics is the highest-paying niche.",topColleges:["IIT Madras","IIT Delhi","IIT Guwahati","VIT Vellore"],topRecruiters:["Biocon","Serum Institute","Dr. Reddy's","Cipla","Bharat Biotech"],avgCTC:"₹4-10 LPA (₹12-25 with MS/PhD)"},children:{}}}},
"bsc_math":{label:"B.Sc. Mathematics",icon:"📐",info:{benefits:["Pure analytical foundation","Leads to data science, actuarial science"],drawbacks:["Fewer direct industry jobs","Masters often needed"],tip:"Pair with coding for a powerful combination.",detail:"B.Sc. Mathematics provides one of the strongest analytical foundations. Graduates excel in quantitative finance, data science, actuarial science, and research. ISI Kolkata and CMI Chennai are globally respected.",topColleges:["ISI Kolkata","CMI Chennai","St. Stephen's Delhi","IISc Bangalore"],topRecruiters:["Goldman Sachs (quant)","WorldQuant","DE Shaw","Actuarial firms"],avgCTC:"₹5-20 LPA (with specialization)"},children:{}},
"architecture":{label:"Architecture (B.Arch)",icon:"🏛️",info:{benefits:["Creative + technical blend","5-year degree","Growing smart city demand"],drawbacks:["Long course (5 years)","Portfolio-heavy","Income grows slowly"],tip:"Keep a sketch diary — observation is an architect's superpower.",detail:"Architecture is a 5-year professional degree covering building design, sustainability, and urban planning. Admission through JEE Main Paper 2 or NATA. Smart Cities Mission and green building certifications are creating new demand.",topColleges:["IIT Kharagpur","IIT Roorkee","SPA Delhi","CEPT Ahmedabad","JJ College Mumbai"],topRecruiters:["Hafeez Contractor","CP Kukreja","Morphogenesis","Studio Lotus","DLF"],avgCTC:"₹4-12 LPA"},children:{}},
"merchant_navy":{label:"Merchant Navy",icon:"🚢",info:{benefits:["Tax-free salary","Travel the world","Quick career growth"],drawbacks:["Months away from family","Physically demanding","Strict medical requirements"],tip:"IMU entrance — apply in Class 12.",detail:"Merchant Navy offers one of the highest-paying careers after Class 12. Officers earn ₹6-20 LPA (tax-free), with captains earning ₹30-60 LPA. The trade-off is 6-9 months at sea away from family.",topColleges:["IMU Chennai","IMU Mumbai","TMI Pune","Anglo Eastern Academy"],topRecruiters:["Maersk","MSC","CMA CGM","Synergy Group","Anglo Eastern"],avgCTC:"₹8-25 LPA (tax-free at sea)"},children:{}},
"nda":{label:"NDA / Defence",icon:"🎖️",info:{benefits:["Serve the nation","Free world-class education","Pension + lifetime benefits"],drawbacks:["Rigorous training","Postings across India","Risk involved"],tip:"Start physical fitness prep in Class 11.",detail:"NDA in Pune is among the world's first tri-service academies. Entry through UPSC NDA exam + SSB interview. Cadets receive a 3-year degree alongside military training, completely free.",topColleges:["NDA Khadakwasla","IMA Dehradun","Naval Academy Ezhimala","AFA Hyderabad"],topRecruiters:["Indian Army","Indian Navy","Indian Air Force"],avgCTC:"₹8-15 LPA + perks (housing, healthcare)"},children:{}}}},
"pcb":{label:"PCB (Physics, Chemistry, Biology)",icon:"🧬",info:{benefits:["Pathway to medicine, biotech, pharma","Helping humanity directly","Research opportunities"],drawbacks:["NEET extremely competitive","Very long education path","High pressure"],tip:"Start NEET prep in Class 11 if targeting MBBS."},children:{
"mbbs":{label:"MBBS (Medicine)",icon:"🩺",info:{benefits:["Most respected profession","Direct impact on lives","Job security","High earning after specialization"],drawbacks:["5.5 years + specialization","NEET extremely competitive","Emotional toll"],tip:"Shadow a doctor before committing.",detail:"MBBS is a 5.5-year degree (4.5 academics + 1 internship) with ~20 lakh NEET aspirants competing for ~1 lakh seats. Government college costs ₹50K-5 lakh total vs private at ₹50 lakh-1 crore. Most doctors pursue MD/MS through NEET PG.",topColleges:["AIIMS Delhi","CMC Vellore","JIPMER","AFMC Pune","Maulana Azad","Grant Medical Mumbai"],topRecruiters:["AIIMS","Apollo Hospitals","Fortis","Max Healthcare","Medanta"],avgCTC:"₹8-15 LPA (MBBS); ₹20-60 LPA+ (post-specialization)"},children:{
"md_ms":{label:"MD / MS (Specialization)",icon:"🏥",info:{benefits:["Expert status","Private practice potential"],drawbacks:["3 more years","NEET PG competitive","Sleep deprivation"],tip:"Follow interest, not just money — burnout is real.",detail:"MD/MS are 3-year postgraduate degrees. Highest-earning specializations include Dermatology, Radiology, Orthopaedics, and Cardiology. Super-specialization (DM/MCh) commands ₹50 LPA to ₹2 Cr+ in private practice.",topColleges:["AIIMS Delhi","CMC Vellore","JIPMER","PGI Chandigarh","NIMHANS"],topRecruiters:["Apollo","Fortis","Medanta","Private practice"],avgCTC:"₹20-60 LPA (₹1-2 Cr private practice for top specializations)"},children:{}}}},
"bds":{label:"BDS (Dentistry)",icon:"🦷",info:{benefits:["Shorter than MBBS","Own clinic potential","Growing cosmetic market"],drawbacks:["Lower earning initially","Oversaturated in cities"],tip:"Cosmetic and implant dentistry are where the money is.",detail:"BDS is a 4-year course + 1-year internship. Dentists who specialize in cosmetic dentistry, implantology, or orthodontics can earn very well. Own clinic setup costs ₹10-30 lakh.",topColleges:["Maulana Azad Delhi","Manipal","SDM Dharwad","SRM Dental"],topRecruiters:["Clove Dental","Sabka Dentist","Apollo Dental","Own clinic"],avgCTC:"₹3-8 LPA (employed); ₹8-25 LPA (own clinic)"},children:{}},
"pharmacy":{label:"B.Pharm (Pharmacy)",icon:"💊",info:{benefits:["Growing pharma industry","Drug development","Healthcare stability"],drawbacks:["Regulatory heavy","Moderate starting salary"],tip:"Clinical research and pharmacovigilance are booming.",detail:"India is the 'pharmacy of the world' — 60% of global vaccines and 20% of generic medicines. B.Pharm graduates work in drug formulation, quality control, regulatory affairs, and clinical research.",topColleges:["NIPER","ICT Mumbai","BIT Mesra","Manipal","Jamia Hamdard"],topRecruiters:["Sun Pharma","Dr. Reddy's","Cipla","Lupin","Biocon","Divis Labs"],avgCTC:"₹3-8 LPA (₹8-18 with M.Pharm)"},children:{}},
"nursing":{label:"B.Sc. Nursing",icon:"🏥",info:{benefits:["Global demand","Job security","Much higher pay abroad"],drawbacks:["Physically demanding","Undervalued in India","Shift work"],tip:"International license (NCLEX/NMC) can 5x your salary.",detail:"India produces 50,000+ nursing graduates annually. International opportunities in US (NCLEX-RN), UK (NMC), and UAE offer significantly higher salaries. In India, specializations in ICU and oncology nursing command premiums.",topColleges:["AIIMS Delhi","CMC Vellore","JIPMER","Apollo School of Nursing"],topRecruiters:["AIIMS","Apollo","Fortis","UK NHS (abroad)","US hospitals (abroad)"],avgCTC:"₹3-6 LPA (India); ₹25-60 LPA (US/UK)"},children:{}},
"veterinary":{label:"Veterinary Science",icon:"🐾",info:{benefits:["Serve animals","Govt roles","Dairy & poultry industry"],drawbacks:["Rural postings","Lower pay than human medicine"],tip:"Urban pet care is booming — very profitable.",detail:"BVSc is a 5-year degree covering animal anatomy, surgery, and livestock management. India's ₹9 lakh crore livestock sector depends on veterinarians. Urban pet care is a high-growth segment.",topColleges:["IVRI Bareilly","Bombay Veterinary College","GADVASU Ludhiana"],topRecruiters:["Govt Animal Husbandry","Amul","NDDB","Mars Petcare","Own clinic"],avgCTC:"₹4-10 LPA (govt); ₹8-25 LPA (own clinic)"},children:{}}}},
"pcmb":{label:"PCMB (All four subjects)",icon:"🎯",info:{benefits:["Maximum flexibility — JEE + NEET eligible","Can decide later"],drawbacks:["Extremely heavy workload","Hard to excel in all four"],tip:"Only if genuinely undecided AND can handle the workload."},children:{}}}},
"commerce":{label:"Commerce Stream",icon:"📊",info:{benefits:["Strong business acumen","CA, MBA, finance pathways","Stable careers"],drawbacks:["'Less prestigious' perception","Needs self-driven learning"],tip:"Commerce + tech skills = unstoppable."},children:{
"ca":{label:"Chartered Accountancy (CA)",icon:"🧾",info:{benefits:["Highly respected","Excellent earning potential","Independent practice","Global recognition"],drawbacks:["Very low pass rates (~5-10%)","4-5 years, 3 levels","Articleship demanding"],tip:"Start CA Foundation right after 12th.",detail:"CA is India's premier accounting qualification (ICAI). The 3-level journey takes 4-5 years. CAs work in auditing, taxation, and corporate finance. Big 4 firms pay ₹8-25 LPA, while experienced practitioners earn ₹30-80 LPA+.",topColleges:["ICAI (self-study + coaching)"],topRecruiters:["Deloitte","PwC","EY","KPMG","Grant Thornton","Reliance","Tata Group"],avgCTC:"₹8-25 LPA (employed); ₹15-80 LPA (practice)"},children:{}},
"cs_prof":{label:"Company Secretary (CS)",icon:"📋",info:{benefits:["Corporate governance expert","Independent practice","Board-level interactions"],drawbacks:["Less known than CA","Low pass rates"],tip:"CS + CA combo = corporate governance powerhouse.",detail:"Company Secretaries ensure corporate legal and regulatory compliance. ICSI conducts the 3-level exam. Stricter governance norms post-Companies Act 2013 have increased demand.",topColleges:["ICSI (self-study + coaching)"],topRecruiters:["Reliance","Tata Group","Infosys","Listed companies (mandatory for listed cos)"],avgCTC:"₹5-15 LPA"},children:{}},
"bcom":{label:"B.Com / BBA",icon:"💼",info:{benefits:["Broad business education","MBA preparation","Entrepreneurship ready"],drawbacks:["Generic without specialization","Lower starting salaries"],tip:"Internships and certifications matter more than marks.",detail:"B.Com and BBA are stepping stones to MBA, CA, CS, and professional certifications. Use the 3 years for internships, certifications (Tally, financial modelling), and exam preparation.",topColleges:["SRCC Delhi","St. Xavier's Mumbai","Christ University","Loyola Chennai","Hindu College Delhi"],topRecruiters:["Deloitte","EY","KPMG","HDFC Bank","Amazon (ops)"],avgCTC:"₹3-8 LPA (B.Com); ₹15-40 LPA (post top MBA)"},children:{}},
"economics":{label:"B.A. Economics",icon:"📈",info:{benefits:["Analytical + social science","Policy, consulting, finance","UPSC friendly"],drawbacks:["Abstract at higher levels","Needs quantitative skills"],tip:"Economics + data analytics is a powerful combo.",detail:"Economics programs from DSE, JNU, ISI, and Ashoka produce graduates who excel in policy, consulting, and finance. Modern economics is increasingly computational. Highly valued for UPSC Civil Services.",topColleges:["DSE Delhi","JNU","ISI Kolkata","Ashoka University","IGIDR Mumbai"],topRecruiters:["RBI","NITI Aayog","World Bank","McKinsey","BCG","Goldman Sachs"],avgCTC:"₹5-15 LPA (varies by institution)"},children:{}},
"banking":{label:"Banking & Finance",icon:"🏧",info:{benefits:["Stable career","Govt bank jobs","Private banks pay well"],drawbacks:["Competitive exams","Sales pressure in private banks"],tip:"CFA or FRM certification makes you stand out.",detail:"Govt banks (SBI, PNB) recruit through IBPS with job security and pensions. Private banks (HDFC, ICICI) offer higher salaries. Investment banking (Goldman, JP Morgan) is the elite tier at ₹15-40 LPA.",topColleges:["Any graduation for bank exams","IIMs for investment banking"],topRecruiters:["SBI","HDFC Bank","ICICI","Goldman Sachs","JP Morgan","Razorpay","Zerodha"],avgCTC:"₹4-8 LPA (govt); ₹15-40 LPA (investment banking)"},children:{}}}},
"arts":{label:"Arts / Humanities",icon:"🎨",info:{benefits:["Creative expression","Diverse paths — law, media, design, civil services","Critical thinking"],drawbacks:["Often undervalued","Lower average starting salaries"],tip:"Arts is not a backup — it's a launchpad."},children:{
"law":{label:"Law (BA LLB / LLB)",icon:"⚖️",info:{benefits:["Prestigious profession","Corporate law pays very well","Social impact"],drawbacks:["5-year integrated course","CLAT competitive"],tip:"Moot courts and internships from year 1 are crucial.",detail:"Law has transformed from litigation-dominated to spanning corporate law, IP, tech law, and policy. Top NLU graduates receive ₹15-30 LPA offers from Tier 1 firms. CLAT is the entrance exam for NLUs.",topColleges:["NLSIU Bangalore","NALSAR Hyderabad","NLU Delhi","NUJS Kolkata"],topRecruiters:["AZB & Partners","Cyril Amarchand","Trilegal","Khaitan & Co","Shardul Amarchand"],avgCTC:"₹12-28 LPA (top NLUs)"},children:{}},
"design":{label:"Design (B.Des)",icon:"🎭",info:{benefits:["High UX/UI demand","Creative fulfillment","Tech + art intersection","Freelance-friendly"],drawbacks:["Portfolio-dependent","Subjective evaluation"],tip:"Start building a portfolio — NID and NIFT love raw creativity.",detail:"Design spans UX/UI, product design, fashion, and animation. Tech industry's appetite for designers is insatiable. Admission through NID DAT, NIFT entrance, UCEED.",topColleges:["NID Ahmedabad","NIFT Delhi","IDC IIT Bombay","Srishti Bangalore"],topRecruiters:["Google","Microsoft","Flipkart","Swiggy","Adobe","Design studios"],avgCTC:"₹6-20 LPA"},children:{}},
"journalism":{label:"Journalism & Mass Comm",icon:"📰",info:{benefits:["Dynamic career","Digital media boom","Storytelling skills"],drawbacks:["Irregular hours","Modest starting pay"],tip:"Start a blog or YouTube channel — your portfolio IS your resume.",detail:"Digital revolution has created new opportunities — content creation, social media, data journalism, podcasts. Traditional newsrooms shrink but digital-first publications hire.",topColleges:["IIMC Delhi","ACJ Chennai","Xavier's Mumbai","Jamia Millia"],topRecruiters:["India Today","The Hindu","Economic Times","BBC India","YouTube/digital platforms"],avgCTC:"₹3-10 LPA (traditional); ₹5-25 LPA (digital)"},children:{}},
"psychology":{label:"B.A. Psychology",icon:"🧠",info:{benefits:["Mental health awareness growing","Counselling in demand","HR and OB roles"],drawbacks:["Masters mandatory for practice","Low starting pay","Long clinical path"],tip:"Clinical psychology needs RCI license (M.Phil mandatory).",detail:"Psychology is experiencing a renaissance. Clinical psychologists, organizational psychologists, UX researchers, and counsellors are in demand. Online therapy platforms are expanding access.",topColleges:["Christ University","Lady Shri Ram","TISS Mumbai","NIMHANS","Ambedkar University"],topRecruiters:["Hospitals","Schools","Corporate HR","Practo","Amaha","NGOs"],avgCTC:"₹3-8 LPA (MA); ₹8-20 LPA (M.Phil Clinical)"},children:{}},
"polsci":{label:"Political Science",icon:"🌐",info:{benefits:["UPSC alignment","Think tanks","Diplomatic service"],drawbacks:["Limited private sector","Academic-oriented"],tip:"IR specialization opens doors to UN and embassies."},children:{}},
"teaching":{label:"Teaching / Education",icon:"👩‍🏫",info:{benefits:["Noble profession","Job security","Work-life balance"],drawbacks:["Lower private salaries","TET/CTET required"],tip:"EdTech has opened ₹10-25 LPA opportunities for good teachers.",detail:"Teaching spans govt schools (TET/CTET), private schools, college teaching (NET/SET), coaching, and EdTech. The coaching industry and YouTube content creation have created teacher-entrepreneurs earning ₹10-50 LPA.",topColleges:["B.Ed programs","NET/SET qualification"],topRecruiters:["KVS","NVS","Allen","FIITJEE","Unacademy","PhysicsWallah"],avgCTC:"₹3-8 LPA (school); ₹8-25 LPA (coaching/EdTech)"},children:{}}}},
"vocational":{label:"Vocational / Skill-Based",icon:"🛠️",info:{benefits:["Practical job-ready skills","Earn while learning","Growing respect for trades"],drawbacks:["Social stigma exists","Lower ceiling without further education"],tip:"Germany, Australia, Canada have huge demand for skilled Indian workers."},children:{
"iti":{label:"ITI / Diploma",icon:"🔩",info:{benefits:["Job-ready in 1-2 years","Govt + private roles"],drawbacks:["Perception issues","Lower starting salary"],tip:"Explore Germany's Ausbildung programs.",detail:"ITIs and polytechnics offer the fastest route to employment for hands-on learners. Lateral entry to B.Tech (2nd year) is possible for diploma holders.",topColleges:["Government ITIs","Government Polytechnics"],topRecruiters:["Indian Railways","ONGC","SAIL","BHEL","Tata Motors","Maruti"],avgCTC:"₹2-5 LPA (ITI); ₹3-7 LPA (diploma)"},children:{}},
"hospitality":{label:"Hotel Management",icon:"🏨",info:{benefits:["Global opportunities","Cruise ships, luxury hotels"],drawbacks:["Long standing hours","Weekend work"],tip:"International hotel chains have management trainee programs.",detail:"Hotel Management covers food production, F&B service, front office, and hospitality management. International placements in Dubai, Singapore, and Europe offer higher packages.",topColleges:["IHM Mumbai","IHM Delhi","IHM Bangalore","Welcomgroup Manipal"],topRecruiters:["Taj Hotels","Oberoi","Marriott","Hyatt","ITC Hotels"],avgCTC:"₹3-8 LPA (India); ₹8-20 LPA (international)"},children:{}},
"paramedical":{label:"Paramedical Courses",icon:"🩻",info:{benefits:["Short duration","Hospital jobs available","Growing healthcare"],drawbacks:["Capped growth","Repetitive work"],tip:"Physiotherapy and radiology have best growth.",detail:"Paramedical courses train lab technicians, radiographers, physiotherapists, and EMTs. Physiotherapy (BPT) is a 4.5-year degree with excellent prospects in sports and neuro-rehab.",topColleges:["CMC Vellore","Manipal","AIIMS allied health"],topRecruiters:["Apollo","Fortis","Max","Dr. Lal PathLabs","SRL Diagnostics"],avgCTC:"₹2-6 LPA (technician); ₹4-12 LPA (physio)"},children:{}}}}
}},
"11-12":{label:"Classes 11–12",description:"Specialization begins — choose wisely!",icon:"🎯",children:{
"competitive":{label:"Competitive Exams",icon:"📝",info:{benefits:["Structured path to top institutes","Coaching ecosystem developed"],drawbacks:["Immense pressure","Mental health impact"],tip:"Students who sleep well and exercise perform better."},children:{
"jee":{label:"JEE Main + Advanced",icon:"🎯",info:{benefits:["IITs globally recognized","Alumni network priceless"],drawbacks:["~10K IIT seats vs 12L aspirants","2 years intense prep"],tip:"Quality of preparation > quantity of hours.",detail:"JEE is India's most prestigious engineering entrance — Main for NITs/IIITs and screening, Advanced for IITs. Around 12 lakh students appear, competing for ~16,000 IIT seats. Tests Physics, Chemistry, and Mathematics at advanced level.",topColleges:["IIT Bombay","IIT Delhi","IIT Madras","NIT Trichy","BITS Pilani"],avgCTC:"Depends on college — ₹6 LPA (lower NITs) to ₹40 LPA+ (top IITs CSE)"},children:{}},
"neet":{label:"NEET UG",icon:"🩺",info:{benefits:["Single exam for all medical colleges","Clear NCERT syllabus"],drawbacks:["20 lakh+ aspirants","Private colleges ₹50L-1Cr"],tip:"NCERT is the bible — read it 5 times before reference books.",detail:"NEET is the sole gateway to MBBS, BDS, AYUSH, and nursing. 200 MCQs in 3hr 20min testing Physics, Chemistry, Biology. Govt medical colleges at ₹50K/year vs private at ₹50L-1Cr.",topColleges:["Leads to: AIIMS, JIPMER, CMC Vellore, AFMC, Maulana Azad"],avgCTC:"N/A — leads to MBBS"},children:{}},
"clat":{label:"CLAT",icon:"⚖️",info:{benefits:["Gateway to NLUs","Less competition than JEE/NEET"],drawbacks:["Aptitude-based","Current affairs heavy"],tip:"Read newspapers daily — CLAT rewards breadth over depth.",detail:"CLAT tests English, Current Affairs, Legal Reasoning, Logical Reasoning, and Quantitative Techniques through passage-based questions for admission to 22 NLUs.",topColleges:["NLSIU Bangalore","NALSAR","NLU Delhi","NUJS Kolkata"],avgCTC:"₹12-28 LPA from top NLUs"},children:{}},
"cuet":{label:"CUET",icon:"🏫",info:{benefits:["Single exam for 40+ central universities","Levels playing field"],drawbacks:["Pattern still evolving","Logistical issues"],tip:"Pick domain subjects carefully — CUET rewards specialization.",detail:"CUET replaced board-marks-based cutoffs at DU, JNU, BHU, and 40+ central universities since 2022. Tests domain subjects, General Test, and Language."},children:{}}}},
"alternative":{label:"Alternative Paths",icon:"🔀",info:{benefits:["Not everyone needs a traditional degree","Skill economy growing"],drawbacks:["Social pressure","Fewer safety nets"],tip:"Unconventional path with a plan beats conventional path without one."},children:{
"abroad_ug":{label:"Study Abroad (UG)",icon:"✈️",info:{benefits:["World-class education","Global exposure","Immigration pathways"],drawbacks:["₹20-60 lakh+ cost","Cultural adjustment","Visa uncertainties"],tip:"SAT + extracurriculars + essays > 12th marks for US.",detail:"US, UK, Canada, Australia, Germany are top destinations. US uses holistic admissions (SAT, essays, extracurriculars). Germany offers tuition-free programs. Post-study work visas provide career entry.",topColleges:["MIT, Stanford, Harvard (US)","Oxford, Cambridge (UK)","UofT, McGill (Canada)","TU Munich (Germany — free)"],avgCTC:"Varies — $60-150K in US"},children:{}},
"gap_year":{label:"Gap Year",icon:"🧭",info:{benefits:["Discover interests","Mental health reset"],drawbacks:["Social stigma in India","Can lose momentum"],tip:"Structured gap year with goals = gold. Unplanned = risky."},children:{}},
"freelancing":{label:"Freelancing / Digital Skills",icon:"💻",info:{benefits:["Start earning at 18","Global clients","Portfolio > degree"],drawbacks:["No stable income initially","Self-marketing needed"],tip:"Pick ONE skill, get really good, build 5 portfolio pieces.",detail:"High-demand freelance skills: web development, graphic design, video editing, copywriting. Indian freelancers benefit from currency advantage — $30-50/hr = ₹15-25 LPA+.",topColleges:["Online learning (Coursera, Udemy, YouTube)"],topRecruiters:["Upwork","Fiverr","Toptal","Direct clients via LinkedIn"],avgCTC:"₹3-25 LPA (depends on skill and niche)"},children:{}}}}
}},
"graduation":{label:"Graduation",description:"Degree in progress — plan your next move!",icon:"🎓",children:{
"higher_ed":{label:"Higher Education",icon:"📚",info:{benefits:["Deeper expertise","Better career positioning"],drawbacks:["2-5 more years","Opportunity cost","Expensive abroad"],tip:"Only pursue if it adds clear value — not as a default."},children:{
"mtech":{label:"M.Tech / MS",icon:"⚙️",info:{benefits:["Specialization depth","GATE scholarship for M.Tech","MS abroad = immigration"],drawbacks:["2-3 years more","ROI unclear for some branches"],tip:"India: GATE → IIT M.Tech (free + stipend). Abroad: GRE → US/Germany MS.",detail:"M.Tech from IITs via GATE is fully funded with ₹12,400/month stipend — India's best-value higher education. MS abroad costs ₹25-60 lakh but provides global exposure. Germany's tuition-free programs are underexplored.",topColleges:["IIT Bombay","IIT Madras","IISc","Stanford, CMU (US)","TU Munich (Germany)"],topRecruiters:["Google","Microsoft","Intel","Qualcomm","Samsung Research","Nvidia"],avgCTC:"₹12-30 LPA (M.Tech); $100-180K (MS US)"},children:{}},
"mba":{label:"MBA",icon:"📊",info:{benefits:["Career accelerator","₹15-40 LPA from IIMs","Network worth crores"],drawbacks:["CAT competitive","₹15-25L fees","2 years opportunity cost"],tip:"2-4 years work experience before MBA gives best ROI.",detail:"MBA with CAT as primary entrance for IIMs. IIM ABC produce median packages of ₹25-35 LPA. Valuable as career switch tool — engineers to consulting/finance. Specializations: finance, marketing, operations, analytics.",topColleges:["IIM Ahmedabad","IIM Bangalore","IIM Calcutta","ISB Hyderabad","XLRI","FMS Delhi"],topRecruiters:["McKinsey","BCG","Bain","Goldman Sachs","Amazon","HUL","P&G"],avgCTC:"₹25-35 LPA (IIM ABC median)"},children:{}},
"abroad_ms":{label:"Study Abroad (Masters)",icon:"🌍",info:{benefits:["Global education","Immigration pathway","Better research infra"],drawbacks:["₹25-60 lakh investment","Visa uncertainty"],tip:"Germany offers tuition-free MS — explore DAAD scholarships.",detail:"US remains top for STEM MS with 3-year OPT. Germany offers tuition-free public universities. Canada's PR pathway makes it attractive. ROI depends on university, program, and job market.",topColleges:["MIT, Stanford, CMU (US)","TU Munich, RWTH Aachen (Germany)","UofT, Waterloo (Canada)"],topRecruiters:["Google, Amazon, Microsoft (US)","SAP, Siemens (Germany)","Shopify, RBC (Canada)"],avgCTC:"$80-180K (US); €50-80K (Germany)"},children:{}}}},
"placements":{label:"Placements / Jobs",icon:"💼",info:{benefits:["Start earning immediately","Practical experience","Financial independence"],drawbacks:["Entry-level modest","First job may not be dream job"],tip:"First job is for learning, not earning. Optimize for growth."},children:{
"tech":{label:"Tech / IT Roles",icon:"💻",info:{benefits:["Largest campus recruiter","₹4-20 LPA","Remote options"],drawbacks:["Service companies monotonous","Bench periods","Support roles initially"],tip:"DSA + system design + projects = placement trifecta.",detail:"IT sector is India's largest campus recruiter — mass (TCS, Infosys at ₹3.5-7 LPA) to dream (Amazon, Microsoft at ₹15-40 LPA) to super-dream (Google, Goldman at ₹30-80 LPA).",topColleges:["IITs","NITs","BITS","IIIT Hyderabad"],topRecruiters:["Google","Microsoft","Amazon","Goldman Sachs","TCS","Infosys","Wipro"],avgCTC:"₹3.5-7 LPA (mass); ₹12-25 LPA (dream); ₹30-80 LPA (super-dream)"},children:{}},
"consulting":{label:"Consulting",icon:"📋",info:{benefits:["MBB prestige","Steep learning curve","Diverse problems"],drawbacks:["80+ hour weeks","Up-or-out culture","Burnout"],tip:"Case interview prep is everything — practice 50+ cases.",detail:"MBB (McKinsey, BCG, Bain) offers rapid learning, diverse exposure, and strong exit opportunities. Entry through top IIMs or IITs. Interview = case studies + behavioral.",topColleges:["IIM ABC","ISB","IIT Bombay","XLRI"],topRecruiters:["McKinsey","BCG","Bain","Kearney","Accenture Strategy","Deloitte Consulting"],avgCTC:"₹15-30 LPA (entry); ₹40-80 LPA (Partner)"},children:{}},
"govt":{label:"Government Exams",icon:"🏛️",info:{benefits:["Job security","Pension + benefits","Respect"],drawbacks:["1-5 year preparation","Low selection rates","Age limit"],tip:"Have a Plan B — average UPSC aspirant takes 3-4 attempts.",detail:"UPSC (IAS/IPS) is most prestigious but ~0.1% selection rate. SSC, Banking, Railways offer more accessible alternatives. Key: manage uncertainty with a backup plan.",topColleges:["Any graduation qualifies","Coaching: Vajiram & Ravi, Vision IAS, Drishti IAS"],topRecruiters:["UPSC (IAS, IPS, IFS)","SSC (CGL, CHSL)","IBPS/SBI","Railways"],avgCTC:"₹6-12 LPA (Group B); ₹10-18 LPA (IAS starting)"},children:{}}}},
"certifications":{label:"Certifications",icon:"📜",info:{benefits:["Focused skill acquisition","Industry-recognized","Done alongside degree"],drawbacks:["Some expensive","Certificate ≠ competence"],tip:"Only invest in certs hiring managers actually ask for."},children:{
"cloud":{label:"AWS / Azure / GCP",icon:"☁️",info:{benefits:["Cloud skills in massive demand","₹2-8 LPA salary bump"],drawbacks:["Exam fees ₹10-25K","Hands-on > cert alone"],tip:"AWS Solutions Architect Associate — start there.",detail:"Cloud certifications validate skills on AWS (~32% market share), Azure (~22%), GCP (~11%). Most popular: AWS Solutions Architect Associate.",topColleges:["Self-study: A Cloud Guru, Stephane Maarek (Udemy)"],topRecruiters:["Amazon","Microsoft","Google","Accenture","TCS","startups"],avgCTC:"₹2-8 LPA bump with relevant experience"},children:{}},
"finance_cert":{label:"CFA / FRM",icon:"📈",info:{benefits:["CFA: gold standard in finance","₹10-30 LPA with experience"],drawbacks:["3 levels over 2-4 years","40-50% pass rates"],tip:"Start CFA Level 1 in final year.",detail:"CFA covers ethics, portfolio management, equity, fixed income, and derivatives across 3 levels. FRM focuses on risk management (2 parts). Both globally recognized.",topColleges:["Self-study: CFA Institute materials, Kaplan Schweser"],topRecruiters:["Goldman Sachs","JP Morgan","HDFC AMC","Kotak AMC","Edelweiss"],avgCTC:"₹8-15 LPA (L1); ₹15-40 LPA (charterholder)"},children:{}}}}
}},
"post-grad":{label:"Post-Graduation",description:"Specialize and accelerate!",icon:"🎓",children:{
"phd":{label:"PhD / Research",icon:"🔬",info:{benefits:["Domain expert","Academic career","₹30-40K/month fellowship"],drawbacks:["4-6 years","Low stipend","Isolation","Tough job market"],tip:"Choose your advisor carefully — matters more than the university.",detail:"PhD is a 4-6 year research commitment producing new knowledge. CSIR/UGC provides ₹31-35K/month fellowships. The academic job market is competitive but industry R&D labs (Google, Microsoft) are alternatives.",topColleges:["IISc Bangalore","IIT Bombay","IIT Madras","TIFR","NCBS"],topRecruiters:["IITs/IISc (faculty)","Google Research","Microsoft Research","IBM","TCS Research"],avgCTC:"₹31-35K/month (fellowship); ₹12-25 LPA (Asst Professor); ₹25-60 LPA (industry R&D)"},children:{}},
"prof_masters":{label:"Professional Masters",icon:"📖",info:{benefits:["Specialized expertise","Career acceleration","Higher salary band"],drawbacks:["Time + money","Not all programs equal"],tip:"ROI varies wildly — tier-1 and tier-3 programs are completely different."},children:{
"exec_mba":{label:"Executive MBA",icon:"👔",info:{benefits:["For working professionals","Weekend/online formats","Immediate salary jump"],drawbacks:["Exhausting with job","Less immersive","Quality varies"],tip:"ISB, IIM executive programs have best brand value.",detail:"Executive MBA programs cater to working professionals with 5-15 years of experience, offering weekend or modular formats without leaving the job.",topColleges:["ISB Hyderabad","IIM Bangalore (EPGP)","IIM Calcutta (PGPEX)","XLRI","Great Lakes"],topRecruiters:["Career acceleration within current company or switch"],avgCTC:"₹5-15 LPA salary bump typical"},children:{}},
"mca":{label:"MCA / Career Switch to Tech",icon:"💻",info:{benefits:["Non-CS to tech switch","NIMCET for top NITs"],drawbacks:["2-3 years","'Not real CS' stigma"],tip:"Build a strong GitHub profile during MCA.",detail:"MCA allows non-CS graduates to transition into tech. NIMCET entrance for top NITs. The key is self-learning beyond curriculum — DSA, projects, and open-source.",topColleges:["NIT Trichy","NIT Warangal","NIT Allahabad","JNU","BHU"],topRecruiters:["TCS","Infosys","Wipro","Amazon","Microsoft (through good DSA skills)"],avgCTC:"₹6-15 LPA (with strong coding skills)"},children:{}}}}
,
"transition":{label:"Career Transition",icon:"🔄",info:{benefits:["Fresh start in a field you love","Transferable skills valuable"],drawbacks:["Starting salary may drop","Steep learning curve","Imposter syndrome"],tip:"Transition gradually — freelance in the new field first."},children:{
"tech_switch":{label:"Non-Tech → Tech",icon:"💻",info:{benefits:["Tech pays more","Coding bootcamps (3-6 months)","Remote options"],drawbacks:["Steep learning curve","May start junior","Ageism in some companies"],tip:"Full-stack web dev is the fastest transition path.",detail:"The most common career transition in India. Coding bootcamps, online courses, and self-study enable transitions. Full-stack development, data analytics, and product management are popular landing spots."},children:{}},
"product_mgmt":{label:"Product Management",icon:"📦",info:{benefits:["No specific degree needed","₹15-40 LPA","Strategic + creative + technical"],drawbacks:["Ambiguous role","Hard to break in","Lots of responsibility, little authority"],tip:"Build a side project and write product teardown blogs.",detail:"PMs own the 'what' and 'why' of product development. Breaking in requires demonstrating product thinking through side projects, case studies, and writing."},children:{}}}}
}},
"working":{label:"Working Professionals",description:"Level up from where you are!",icon:"💼",children:{
"growth":{label:"Career Growth",icon:"📈",info:{benefits:["Move up the ladder","Higher compensation","More impact"],drawbacks:["Politics increase","Work-life harder","Skills that got you here won't get you there"],tip:"Visibility matters as much as ability."},children:{
"leadership":{label:"Management / Leadership",icon:"👥",info:{benefits:["People management skills","₹20-60 LPA at senior levels","Executive path"],drawbacks:["Less hands-on","People problems are hard","Meeting-heavy days"],tip:"Read 'The Manager's Path' by Camille Fournier.",detail:"Transitioning from individual contributor to manager is one of the biggest career shifts. It requires developing entirely new skills — delegation, coaching, hiring, conflict resolution, and strategic thinking."},children:{}},
"ic_track":{label:"IC Track (Staff/Principal)",icon:"🧑‍💻",info:{benefits:["Stay technical","₹30-80 LPA at Staff/Principal level","Deep expertise valued"],drawbacks:["Fewer positions at top","Can plateau","Need to stay cutting-edge"],tip:"System design + tech writing + mentoring = Staff Engineer recipe.",detail:"The Individual Contributor track allows engineers to grow without becoming managers. Staff Engineers and Principal Engineers solve organization-wide technical problems and set technical direction."},children:{}},
"intl":{label:"International Career",icon:"🌍",info:{benefits:["2-5x salary","Global experience","Better work-life in some countries"],drawbacks:["Visa challenges","Cultural adjustment","Away from family"],tip:"US (H1B), Canada (Express Entry), Germany (Job Seeker Visa), UAE — research your pathway.",detail:"Common pathways: US H-1B visa (lottery-based), Canada Express Entry (points-based, most accessible), Germany Job Seeker Visa, and UAE employment visas."},children:{}}}},
"side_income":{label:"Side Income",icon:"💰",info:{benefits:["Financial security","Explore interests","Multiple income streams"],drawbacks:["Time management","Burnout risk","Employer restrictions"],tip:"Start with something using your existing skills."},children:{
"content":{label:"Content Creation / Teaching",icon:"📹",info:{benefits:["YouTube, Udemy courses","Passive income potential","Personal brand"],drawbacks:["Consistency required","Results take 6-12 months"],tip:"Technical content on YouTube has massive demand in India.",detail:"Technical YouTube channels, online courses (Udemy, Skillshare), newsletter writing, and LinkedIn content creation are popular side income sources for professionals."},children:{}},
"consulting_side":{label:"Consulting / Freelancing",icon:"📋",info:{benefits:["Premium rates for expertise","₹2-10 lakh/month possible","Flexibility"],drawbacks:["Inconsistent income","Client management"],tip:"Start on Toptal or Upwork — build reputation first.",detail:"Senior professionals can leverage domain expertise for consulting engagements. Platforms like Toptal, Clarity.fm, and direct referrals are common channels."},children:{}},
"investing":{label:"Investing & Wealth",icon:"📊",info:{benefits:["Money working for you","Compound interest","Financial independence"],drawbacks:["Risk of loss","Needs financial literacy","Emotional discipline"],tip:"Start with index funds (Nifty 50), learn 2 years, then explore stocks.",detail:"Systematic investing in index funds, mutual funds, and stocks alongside salary is the most reliable wealth-building strategy. SIP in Nifty 50 index fund is the recommended starting point."},children:{}}}},
"upskilling":{label:"Upskilling",icon:"🔄",info:{benefits:["Stay relevant","Salary bump","Career pivots possible"],drawbacks:["Time commitment","Decision fatigue on what to learn"],tip:"Learn in public — share your journey on LinkedIn."},children:{
"ai_skills":{label:"AI / GenAI Skills",icon:"🤖",info:{benefits:["Every role needs AI literacy","Prompt engineering is real","₹5-15 LPA bump"],drawbacks:["Hype vs reality","Tools change monthly"],tip:"Don't just use ChatGPT — learn to build with AI APIs.",detail:"AI literacy is becoming essential across roles. Understanding how to use AI tools, build AI-powered workflows, and prompt engineer effectively creates significant career advantage."},children:{}},
"soft_skills":{label:"Communication & Soft Skills",icon:"🗣️",info:{benefits:["Differentiator at senior levels","Leadership readiness"],drawbacks:["Hard to measure","Takes years of practice"],tip:"Join Toastmasters — best ROI time investment for your career.",detail:"Public speaking, negotiation, writing, and executive presence become the primary differentiators at senior career levels where technical skills are assumed."},children:{}}}}
}}
};

// ═══════════════════════════════════════════
// BLOG DATA
// ═══════════════════════════════════════════
const DEFAULT_BLOG_DATA = [
{id:1,title:"Why I Chose CS Over Medicine — And What I Wish I Knew",excerpt:"Navigating the PCM vs PCB decision and the unexpected turns that followed.",content:"Making the choice between PCM and PCB in Class 11 felt like the biggest decision of my life. And in many ways, it was.\n\nI was good at both biology and maths. My parents, both doctors, naturally assumed I'd follow tradition. But something about building things — seeing code turn into a working application — fascinated me in a way memorizing anatomical terms never could.\n\nHere's what I wish someone had told me: the choice isn't permanent. Many CS batchmates came from biology backgrounds. Some doctors code on weekends. The rigid boxes we put ourselves in at 16 don't define us at 26.\n\nThat said, there ARE practical implications. MBBS needs biology. Core engineering needs maths. But meta-skills — problem-solving, critical thinking, communication — transfer everywhere.\n\nFollow your curiosity, not expectations or society's rankings. The best career is one where Monday mornings don't feel like punishment.",author:"Arjun Krishnan",authorAvatar:"AK",date:"2026-04-28",readTime:"5 min",tags:["Career Choice","Engineering","Personal Story"],category:"Student Stories"},
{id:2,title:"The Arts Student's Guide to a ₹20 LPA Career",excerpt:"Breaking the myth that humanities degrees lead nowhere. UX Design, Policy, and Data Journalism are hiring.",content:"Let's address the elephant: 'Arts leke kya karega?'\n\nThis question haunted me through college. Today, as a UX Designer at a leading tech company earning well above the 'engineer average,' I have my answer.\n\nFive high-paying careers for arts graduates:\n1. UX/UI Design — understanding human psychology IS the job\n2. Content Strategy — tech companies need people who can WRITE\n3. Data Journalism — storytelling with numbers\n4. Public Policy — think tanks need social scientists\n5. EdTech Curriculum Design — education meets technology\n\nThe key: combine your humanities foundation with one technical skill. Learn Figma. Learn basic Python. That combination makes you rare and valuable.\n\nArts is not a dead end. It's a secret passage.",author:"Priya Menon",authorAvatar:"PM",date:"2026-05-10",readTime:"7 min",tags:["Arts","Career Growth","UX Design"],category:"Career Paths"},
{id:3,title:"NEET vs JEE: An Honest Comparison",excerpt:"Preparation intensity, career outcomes, and lifestyle — a data-driven comparison of India's two biggest exams.",content:"Every year, ~20 lakh students appear for NEET and ~12 lakh for JEE Main. Which is 'harder'? Wrong question.\n\nReframe: which exam ecosystem fits YOUR temperament?\n\nNEET: single exam, one format. Tests biology, chemistry, physics. Rewards memory + application. Finite syllabus.\n\nJEE: two-tier (Main + Advanced). Tests physics, chemistry, maths. Rewards speed + deep problem-solving. Unpredictable questions.\n\nBeyond the exam:\n- MBBS: 5.5 years study, earn properly ~28-30. High ceiling.\n- B.Tech: 4 years, earn at 22. Easier career switches. Lower floor without good college.\n\nMost important factor? Genuine interest. Forced NEET prep when you love coding = misery. And vice versa.\n\nTalk to actual doctors and engineers. Not Instagram highlights — the real ones.",author:"Dr. Rahul Sharma",authorAvatar:"RS",date:"2026-05-02",readTime:"6 min",tags:["NEET","JEE","Comparison"],category:"Exam Guide"}
];
